# -*- coding: utf-8 -*-
"""loading_model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZY8pqA-_3KYDKQjBoB6sGkVF61Zg8Du6
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.utils import plot_model
from keras.models import load_model

model = load_model("/content/model_cnn.h5")

model.summary()

plot_model(model, to_file="model_cnn.png")

#load fashin mnist dataset
(training_images, training_labels), (test_images, test_labels) = keras.datasets.fashion_mnist.load_data()
print(training_images.shape)

#reshape
training_images = training_images.reshape(training_images.shape[0], 28,28,1)
test_images = test_images.reshape(test_images.shape[0], 28,28,1)
print(training_images.shape)

test_loss, test_acc = model.evaluate(test_images, test_labels)
print(test_acc)